In [60]:
from matplotlib import pyplot as plt
from scipy.stats import linregress
import numpy as np
import pandas as pd
from config import api_key
import requests
import json
import datetime as date

In [71]:
tickers = ['AAPL', 'GOOG', 'AMZN']
dfs = []
for annual in tickers:
    annual_url = f"https://financialmodelingprep.com/api/v3/income-statement/{annual}?limit=11&apikey={api_key}"
    response = requests.get(annual_url).json()
    data = pd.json_normalize(response)
    data["tickers"] = annual
    dfs.append(data)

In [72]:
merge_df = pd.concat(dfs)

merge_df

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,revenue,costOfRevenue,...,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink,tickers
0,2022-09-24,AAPL,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,FY,394328000000,223546000000,...,19300000000,99803000000,0.253096,6.150000,6.110000,16215963000,16325819000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
1,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,365817000000,212981000000,...,14527000000,94680000000,0.258818,5.670000,5.610000,16701272000,16864919000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
2,2020-09-26,AAPL,USD,0000320193,2020-10-30,2020-10-29 18:06:25,2020,FY,274515000000,169559000000,...,9680000000,57411000000,0.209136,3.310000,3.280000,17352119000,17528214000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
3,2019-09-28,AAPL,USD,0000320193,2019-10-31,2019-10-30 18:12:36,2019,FY,260174000000,161782000000,...,10481000000,55256000000,0.212381,2.992500,2.972500,18471336000,18595652000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
4,2018-09-29,AAPL,USD,0000320193,2018-11-05,2018-11-05 08:01:40,2018,FY,265595000000,163756000000,...,13372000000,59531000000,0.224142,3.002500,2.977500,19821508000,20000436000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
5,2017-09-30,AAPL,USD,0000320193,2017-11-03,2017-11-03 08:01:37,2017,FY,229234000000,141048000000,...,15738000000,48351000000,0.210924,2.317500,2.302500,20868968000,21006768000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
6,2016-09-24,AAPL,USD,0000320193,2016-10-26,2016-10-26 16:42:16,2016,FY,215639000000,131376000000,...,15685000000,45687000000,0.211868,2.087500,2.077500,21883280000,22001124000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
7,2015-09-26,AAPL,USD,0000320193,2015-10-28,2015-10-28 16:31:09,2015,FY,233715000000,140089000000,...,19121000000,53394000000,0.228458,2.320000,2.305000,23013684000,23172276000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
8,2014-09-27,AAPL,USD,0000320193,2014-10-27,2014-10-27 17:11:55,2014,FY,182795000000,112258000000,...,13973000000,39510000000,0.216144,1.622500,1.612500,24342288000,24490652000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
9,2013-09-28,AAPL,USD,0000320193,2013-10-30,2013-10-29 20:38:28,2013,FY,170910000000,106606000000,...,13118000000,37037000000,0.216705,1.429643,1.419643,25909268000,26086536000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
10,2012-09-29,AAPL,USD,0000320193,2012-10-31,2012-10-31 17:07:19,2012,FY,156508000000,87846000000,...,14030000000,41733000000,0.266651,1.594286,1.576786,26174904000,26469940000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
0,2021-12-31,GOOG,USD,0001652044,2022-02-02,2022-02-01 21:08:02,2021,FY,257637000000,110939000000,...,14701000000,76033000000,0.295117,5.694003,5.610003,13352993991,13553473900,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
1,2020-12-31,GOOG,USD,0001652044,2021-02-03,2021-02-02 20:12:25,2020,FY,182527000000,84732000000,...,7813000000,40269000000,0.220619,2.957501,2.930501,13616313872,13740553816,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
2,2019-12-31,GOOG,USD,0001652044,2020-02-04,2020-02-03 21:03:59,2019,FY,161857000000,71896000000,...,5282000000,34343000000,0.212181,2.479501,2.458001,13851914459,13971114411,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
3,2018-12-31,GOOG,USD,0001652044,2019-02-05,2019-02-04 21:06:38,2018,FY,136819000000,59549000000,...,4177000000,30736000000,0.224647,2.211001,2.185001,13901396520,14066813595,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
4,2017-12-31,GOOG,USD,0001652044,2018-02-06,2018-02-05 20:46:29,2017,FY,110855000000,45583000000,...,14531000000,12662000000,0.114221,0.913500,0.900000,13860968730,14068883261,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
5,2016-12-31,GOOG,USD,0001652044,2017-02-03,2017-02-02 18:13:47,2016,FY,90272000000,35138000000,...,4672000000,19478000000,0.215770,1.416001,1.392501,13755644215,13987786146,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
6,2015-12-31,GOOG,USD,0001652044,2016-02-11,2016-02-11 16:38:35,2015,FY,74989000000,28164000000,...,3303000000,16348000000,0.218005,1.155500,1.142000,13696229917,13858138064,https://www.sec.gov/Archives/edgar/data/165204...,https://www.sec.gov/Archives/edgar/data/165204...,GOOG
7,2014-12-31,GOOG,USD,0001652044,2014-12-31,2014-12-31,2014,FY,66001000000,25691000000,...,3331000000,14444000000,0.218845,1.068500,1.051000,13518694592,13741394503,,,GOOG
8,2013-12-31,GOOG,USD,0001652044,2013-12-31,2013-12-31,2013,FY,59825000000,25858000000,...,2282000000,12920000000,0.215963,1.941001,1.906501,6656917337,6776177289,,,GOOG
9,2012-12-31,GOOG,USD,0001652044,2012-12-31,2012-12-31,2012,FY,50175000000,20634000000,...,2598000000,10737000000,0.213991,1.640501,1.615501,6544257382,6646097341,,,GOOG
10,2011-12-31,GOOG,USD,0001652044,2011-12-31,2011-12-31,2011,FY,37905000000,13188000000,...,2589000000,9737000000,0.256879,1.508501,1.488001,6455557417,6544277382,,,GOOG
0,2021-12-31,AMZN,USD,0001018724,2022-02-04,2022-02-03 18:46:51,2021,FY,469822000000,403507000000,...,4791000000,33364000000,0.071014,3.298000,3.240500,10120000000,10300000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
1,2020-12-31,AMZN,USD,0001018724,2021-02-03,2021-02-02 19:44:10,2020,FY,386064000000,291824000000,...,2863000000,21331000000,0.055252,2.091275,2.091275,10000000000,10200000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
2,2019-12-31,AMZN,USD,0001018724,2020-01-31,2020-01-30 20:46:13,2019,FY,280522000000,205768000000,...,2374000000,11588000000,0.041309,1.149603,1.149603,9880000000,10080000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
3,2018-12-31,AMZN,USD,0001018724,2019-02-01,2019-01-31 20:22:40,2018,FY,232887000000,173183000000,...,1197000000,10073000000,0.043253,1.007300,1.007300,9740000000,10000000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
4,2017-12-31,AMZN,USD,0001018724,2018-02-02,2018-02-01 20:41:15,2017,FY,177866000000,159803000000,...,769000000,3033000000,0.017052,0.316000,0.307500,9600000000,9860000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
5,2016-12-31,AMZN,USD,0001018724,2017-02-10,2017-02-09 17:56:36,2016,FY,135987000000,105884000000,...,1425000000,2371000000,0.017435,0.244938,0.244938,9480000000,9680000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
6,2015-12-31,AMZN,USD,0001018724,2016-01-29,2016-01-28 19:38:11,2015,FY,107006000000,85061000000,...,950000000,596000000,0.005570,0.062474,0.062474,9340000000,9540000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
7,2014-12-31,AMZN,USD,0001018724,2015-01-30,2015-01-29 19:38:08,2014,FY,88988000000,73518000000,...,167000000,-241000000,-0.002708,-0.026082,-0.026082,9240000000,9240000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
8,2013-12-31,AMZN,USD,0001018724,2014-01-31,2014-01-30 21:52:38,2013,FY,74452000000,62766000000,...,161000000,274000000,0.003680,0.029462,0.029462,9140000000,9300000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
9,2012-12-31,AMZN,USD,0001018724,2013-01-30,2013-01-29 19:13:32,2012,FY,61093000000,56954000000,...,428000000,-39000000,-0.000638,-0.004500,-0.004500,9060000000,9060000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
10,2011-12-31,AMZN,USD,0001018724,2012-02-01,2012-01-31 21:58:32,2011,FY,48077000000,37288000000,...,291000000,631000000,0.013125,0.068438,0.068438,9060000000,9220000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN

In [67]:
#Delete Unwanted columns
del_df = merge_df.drop(['reportedCurrency', 'cik', 'acceptedDate', 'costOfRevenue', 'grossProfitRatio', 'researchAndDevelopmentExpenses', 'generalAndAdministrativeExpenses', 'ebitdaratio', 'operatingIncome', 'operatingIncomeRatio', 'totalOtherIncomeExpensesNet', 'incomeBeforeTax', 'incomeTaxExpense', 'netIncomeRatio', 'epsdiluted', 'weightedAverageShsOutDil', 'link', 'finalLink', 'sellingAndMarketingExpenses', 'sellingGeneralAndAdministrativeExpenses', 'otherExpenses', 'costAndExpenses', 'interestIncome', 'interestExpense', 'depreciationAndAmortization', 'ebitda', 'incomeBeforeTaxRatio', 'operatingExpenses', 'tickers'], axis=1)

del_df

,date,symbol,fillingDate,calendarYear,period,revenue,grossProfit,netIncome,eps,weightedAverageShsOut
0,2022-09-24,AAPL,2022-10-28,2022,FY,394328000000,170782000000,99803000000,6.150000,16215963000
1,2021-09-25,AAPL,2021-10-29,2021,FY,365817000000,152836000000,94680000000,5.670000,16701272000
2,2020-09-26,AAPL,2020-10-30,2020,FY,274515000000,104956000000,57411000000,3.310000,17352119000
3,2019-09-28,AAPL,2019-10-31,2019,FY,260174000000,98392000000,55256000000,2.992500,18471336000
4,2018-09-29,AAPL,2018-11-05,2018,FY,265595000000,101839000000,59531000000,3.002500,19821508000
5,2017-09-30,AAPL,2017-11-03,2017,FY,229234000000,88186000000,48351000000,2.317500,20868968000
6,2016-09-24,AAPL,2016-10-26,2016,FY,215639000000,84263000000,45687000000,2.087500,21883280000
7,2015-09-26,AAPL,2015-10-28,2015,FY,233715000000,93626000000,53394000000,2.320000,23013684000
8,2014-09-27,AAPL,2014-10-27,2014,FY,182795000000,70537000000,39510000000,1.622500,24342288000
9,2013-09-28,AAPL,2013-10-30,2013,FY,170910000000,64304000000,37037000000,1.429643,25909268000
10,2012-09-29,AAPL,2012-10-31,2012,FY,156508000000,68662000000,41733000000,1.594286,26174904000
0,2021-12-31,GOOG,2022-02-02,2021,FY,257637000000,146698000000,76033000000,5.694003,13352993991
1,2020-12-31,GOOG,2021-02-03,2020,FY,182527000000,97795000000,40269000000,2.957501,13616313872
2,2019-12-31,GOOG,2020-02-04,2019,FY,161857000000,89961000000,34343000000,2.479501,13851914459
3,2018-12-31,GOOG,2019-02-05,2018,FY,136819000000,77270000000,30736000000,2.211001,13901396520
4,2017-12-31,GOOG,2018-02-06,2017,FY,110855000000,65272000000,12662000000,0.913500,13860968730
5,2016-12-31,GOOG,2017-02-03,2016,FY,90272000000,55134000000,19478000000,1.416001,13755644215
6,2015-12-31,GOOG,2016-02-11,2015,FY,74989000000,46825000000,16348000000,1.155500,13696229917
7,2014-12-31,GOOG,2014-12-31,2014,FY,66001000000,40310000000,14444000000,1.068500,13518694592
8,2013-12-31,GOOG,2013-12-31,2013,FY,59825000000,33967000000,12920000000,1.941001,6656917337
9,2012-12-31,GOOG,2012-12-31,2012,FY,50175000000,29541000000,10737000000,1.640501,6544257382
10,2011-12-31,GOOG,2011-12-31,2011,FY,37905000000,24717000000,9737000000,1.508501,6455557417
0,2021-12-31,AMZN,2022-02-04,2021,FY,469822000000,66315000000,33364000000,3.298000,10120000000
1,2020-12-31,AMZN,2021-02-03,2020,FY,386064000000,94240000000,21331000000,2.091275,10000000000
2,2019-12-31,AMZN,2020-01-31,2019,FY,280522000000,74754000000,11588000000,1.149603,9880000000
3,2018-12-31,AMZN,2019-02-01,2018,FY,232887000000,59704000000,10073000000,1.007300,9740000000
4,2017-12-31,AMZN,2018-02-02,2017,FY,177866000000,18063000000,3033000000,0.316000,9600000000
5,2016-12-31,AMZN,2017-02-10,2016,FY,135987000000,30103000000,2371000000,0.244938,9480000000
6,2015-12-31,AMZN,2016-01-29,2015,FY,107006000000,21945000000,596000000,0.062474,9340000000
7,2014-12-31,AMZN,2015-01-30,2014,FY,88988000000,15470000000,-241000000,-0.026082,9240000000
8,2013-12-31,AMZN,2014-01-31,2013,FY,74452000000,11686000000,274000000,0.029462,9140000000
9,2012-12-31,AMZN,2013-01-30,2012,FY,61093000000,4139000000,-39000000,-0.004500,9060000000
10,2011-12-31,AMZN,2012-02-01,2011,FY,48077000000,10789000000,631000000,0.068438,9060000000

Empty DataFrame
Columns: [Ticker, Filing Date, Calendar Year, Period, Revenue, Gross Profit, Net Income, EPS, Shares Outstanding]
Index: []

In [24]:
#Get Quarterly Statements
tickers1 = ['AAPL', 'GOOG', 'AMZN']
dfs1 = []
for quarter in tickers1:
    quarter_url = f"https://financialmodelingprep.com/api/v3/income-statement/{quarter}?period=quarter&limit=44&apikey={api_key}"
    q_response = requests.get(quarter_url).json()
    data1 = pd.json_normalize(q_response)
    data1["tickers1"] = quarter
    dfs1.append(data1)

In [25]:
combo_df = pd.concat(dfs1)
combo_df

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,revenue,costOfRevenue,...,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink,tickers1
0,2022-09-24,AAPL,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,Q4,90146000000,52051000000,...,3936000000,2.072100e+10,0.229860,1.290000,1.290000,16030382000,16118465000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
1,2022-06-25,AAPL,USD,0000320193,2022-07-29,2022-07-28 18:06:56,2022,Q3,82959000000,47074000000,...,3624000000,1.944200e+10,0.234357,1.200000,1.200000,16162945000,16262203000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
2,2022-03-26,AAPL,USD,0000320193,2022-04-29,2022-04-28 18:03:58,2022,Q2,97278000000,54719000000,...,5129000000,2.501000e+10,0.257098,1.530000,1.510000,16391724000,16519291000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
3,2021-12-25,AAPL,USD,0000320193,2022-01-28,2022-01-27 18:00:58,2022,Q1,123945000000,69702000000,...,6611000000,3.463000e+10,0.279398,2.110000,2.100000,16391724000,16519291000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
4,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,Q4,83360000000,48186000000,...,2697000000,2.055100e+10,0.246533,1.250000,1.240000,16487121000,16635097000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2012-12-31,AMZN,USD,0001018724,2013-01-30,2013-01-29 19:13:32,2012,Q4,21268000000,19740000000,...,194000000,9.800000e+07,0.004608,0.010500,0.010500,9080000000,9220000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
40,2012-09-30,AMZN,USD,0001018724,2012-10-26,2012-10-25 19:35:25,2012,Q3,13806000000,10319000000,...,83000000,-2.740000e+08,-0.019846,-0.029783,-0.029783,9040000000,9200000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
41,2012-06-30,AMZN,USD,0001018724,2012-07-27,2012-07-26 20:02:00,2012,Q2,12834000000,9488000000,...,109000000,7.000000e+06,0.000545,0.000764,0.000764,9020000000,9160000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
42,2012-03-31,AMZN,USD,0001018724,2012-04-27,2012-04-26 21:25:46,2012,Q1,13185000000,10027000000,...,43000000,1.300000e+08,0.009860,0.014130,0.014130,9060000000,9200000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN
43,2011-12-31,AMZN,USD,0001018724,2012-02-01,2012-01-31 21:58:32,2011,Q4,17431000000,13831000000,...,86000000,1.770000e+08,0.010154,0.019239,0.019239,9060000000,9200000000,https://www.sec.gov/Archives/edgar/data/101872...,https://www.sec.gov/Archives/edgar/data/101872...,AMZN

In [28]:
clean_df = combo_df.drop(['reportedCurrency', 'cik', 'acceptedDate', 'costOfRevenue', 'grossProfitRatio', 'researchAndDevelopmentExpenses', 'generalAndAdministrativeExpenses', 'ebitdaratio', 'operatingIncome', 'operatingIncomeRatio', 'totalOtherIncomeExpensesNet', 'incomeBeforeTax', 'incomeTaxExpense', 'netIncomeRatio', 'epsdiluted', 'weightedAverageShsOutDil', 'link', 'finalLink', 'sellingAndMarketingExpenses', 'sellingGeneralAndAdministrativeExpenses', 'otherExpenses', 'costAndExpenses', 'interestIncome', 'interestExpense', 'depreciationAndAmortization', 'ebitda', 'incomeBeforeTaxRatio', 'operatingExpenses', 'tickers1'], axis=1)
clean_df

,date,symbol,fillingDate,calendarYear,period,revenue,grossProfit,netIncome,eps,weightedAverageShsOut
0,2022-09-24,AAPL,2022-10-28,2022,Q4,90146000000,38095000000,2.072100e+10,1.290000,16030382000
1,2022-06-25,AAPL,2022-07-29,2022,Q3,82959000000,35885000000,1.944200e+10,1.200000,16162945000
2,2022-03-26,AAPL,2022-04-29,2022,Q2,97278000000,42559000000,2.501000e+10,1.530000,16391724000
3,2021-12-25,AAPL,2022-01-28,2022,Q1,123945000000,54243000000,3.463000e+10,2.110000,16391724000
4,2021-09-25,AAPL,2021-10-29,2021,Q4,83360000000,35174000000,2.055100e+10,1.250000,16487121000
...,...,...,...,...,...,...,...,...,...,...
39,2012-12-31,AMZN,2013-01-30,2012,Q4,21268000000,1528000000,9.800000e+07,0.010500,9080000000
40,2012-09-30,AMZN,2012-10-26,2012,Q3,13806000000,3487000000,-2.740000e+08,-0.029783,9040000000
41,2012-06-30,AMZN,2012-07-27,2012,Q2,12834000000,3346000000,7.000000e+06,0.000764,9020000000
42,2012-03-31,AMZN,2012-04-27,2012,Q1,13185000000,3158000000,1.300000e+08,0.014130,9060000000
43,2011-12-31,AMZN,2012-02-01,2011,Q4,17431000000,3600000000,1.770000e+08,0.019239,9060000000

In [29]:
#Get Statement Balance for Cash on Hand Info & create another loop
tickers2 = ['AAPL', 'GOOG', 'AMZN']
dfs2 = []


for cash in tickers2:
    cash_url = f"https://financialmodelingprep.com/api/v3/balance-sheet-statement/{cash}?apikey={api_key}&limit=11"
    c_response = requests.get(cash_url).json()
    data2 = pd.json_normalize(c_response)
    data2["tickers2"] = cash
    data2 = data2[["date", "symbol", "fillingDate", "calendarYear", "period", "cashAndCashEquivalents", "shortTermDebt", "longTermDebt"]]
    dfs2.append(data2)

In [30]:
merge2_df = pd.concat(dfs2)
merge2_df

,date,symbol,fillingDate,calendarYear,period,cashAndCashEquivalents,shortTermDebt,longTermDebt
0,2022-09-24,AAPL,2022-10-28,2022,FY,23646000000,2.111000e+10,9.895900e+10
1,2021-09-25,AAPL,2021-10-29,2021,FY,34940000000,1.561300e+10,1.091060e+11
2,2020-09-26,AAPL,2020-10-30,2020,FY,38016000000,1.376900e+10,9.866700e+10
3,2019-09-28,AAPL,2019-10-31,2019,FY,48844000000,1.624000e+10,9.180700e+10
4,2018-09-29,AAPL,2018-11-05,2018,FY,25913000000,2.074800e+10,9.373500e+10
5,2017-09-30,AAPL,2017-11-03,2017,FY,20289000000,1.847300e+10,9.720700e+10
6,2016-09-24,AAPL,2016-10-26,2016,FY,20484000000,1.160500e+10,7.542700e+10
7,2015-09-26,AAPL,2015-10-28,2015,FY,21120000000,1.099900e+10,5.346300e+10
8,2014-09-27,AAPL,2014-10-27,2014,FY,13844000000,6.308000e+09,2.898700e+10
9,2013-09-28,AAPL,2013-10-30,2013,FY,14259000000,0.000000e+00,1.696000e+10
10,2012-09-29,AAPL,2012-10-31,2012,FY,10746000000,0.000000e+00,0.000000e+00
0,2021-12-31,GOOG,2022-02-02,2021,FY,20945000000,2.189000e+09,2.620600e+10
1,2020-12-31,GOOG,2021-02-03,2020,FY,26465000000,1.694000e+09,2.507800e+10
2,2019-12-31,GOOG,2020-02-04,2019,FY,18498000000,1.199000e+09,1.476800e+10
3,2018-12-31,GOOG,2019-02-05,2018,FY,16701000000,0.000000e+00,4.012000e+09
4,2017-12-31,GOOG,2018-02-06,2017,FY,10715000000,0.000000e+00,3.969000e+09
5,2016-12-31,GOOG,2017-02-03,2016,FY,12918000000,0.000000e+00,3.935000e+09
6,2015-12-31,GOOG,2016-02-11,2015,FY,16549000000,3.225000e+09,1.995000e+09
7,2014-12-31,GOOG,2014-12-31,2014,FY,18347000000,2.009000e+09,3.228000e+09
8,2013-12-31,GOOG,2013-12-31,2013,FY,18898000000,3.009000e+09,2.236000e+09
9,2012-12-31,GOOG,2012-12-31,2012,FY,14778000000,2.549000e+09,2.988000e+09
10,2011-12-31,GOOG,2011-12-31,2011,FY,9983000000,1.218000e+09,2.986000e+09
0,2021-12-31,AMZN,2022-02-04,2021,FY,36220000000,0.000000e+00,1.163950e+11
1,2020-12-31,AMZN,2021-02-03,2020,FY,42122000000,0.000000e+00,8.438900e+10
2,2019-12-31,AMZN,2020-01-31,2019,FY,36092000000,0.000000e+00,2.341400e+10
3,2018-12-31,AMZN,2019-02-01,2018,FY,31750000000,0.000000e+00,2.349500e+10
4,2017-12-31,AMZN,2018-02-02,2017,FY,20522000000,0.000000e+00,3.792600e+10
5,2016-12-31,AMZN,2017-02-10,2016,FY,19334000000,0.000000e+00,7.694000e+09
6,2015-12-31,AMZN,2016-01-29,2015,FY,15890000000,0.000000e+00,8.235000e+09
7,2014-12-31,AMZN,2015-01-30,2014,FY,14557000000,0.000000e+00,8.265000e+09
8,2013-12-31,AMZN,2014-01-31,2013,FY,8658000000,0.000000e+00,3.191000e+09
9,2012-12-31,AMZN,2013-01-30,2012,FY,8084000000,0.000000e+00,3.830000e+09
10,2011-12-31,AMZN,2012-02-01,2011,FY,5269000000,0.000000e+00,2.550000e+08

In [64]:
#Clean up DataFrame

date = []
symbol = []
fillingDate = []
calendar_year = []
period = []
revenue = []
gross_profit = []
net_income = []
eps = []
shares_oustanding = []

date.append(response["date"])
symbol.append(response["symbol"])
filling_date.append(response["fillingDate"])
calendar_year.append(response["calendarYear"])
period.append(response["period"])
revenue.append(response["revenue"])
gross_profit.append(response["grossProfit"])
net_income.append(response["netIncome"])
eps.append(response["eps"])
shares_oustanding.append(response["weightedAverageShsOut"])



fiscal_year = pd.DataFrame({"Ticker": symbol,
                           "Filing Date": date,
                           "Calendar Year": calendar_year,
                           "Period": period,
                           "Revenue": revenue,
                           "Gross Profit": gross_profit,
                           "Net Income": net_income,
                           "EPS": eps,
                           "Shares Outstanding": shares_oustanding})
fiscal_year

TypeError: list indices must be integers or slices, not str